# How many distinct terms are in the sequence generated by a^b for 2 <= a <= 100 and 2 <= b <= 100?

def uniquePowers(limit):
  square_list = []
  for a in range(2,limit + 1):
    for b in range(2,limit + 1):
      square_list.append(a**b)
  return len(set(square_list))

def main():
  print(uniquePowers(100))

if __name__ == "__main__":
    main()
